# 📊 Projeto Prático: Uplift Modeling para Retenção de Clientes
---
### Cenário de Negócio
A empresa deseja otimizar o investimento em campanhas de retenção. Em vez de enviar a mesma ação de marketing para todos, queremos identificar apenas os clientes **verdadeiramente persuasíveis**: aqueles que *não* renovariam o contrato sem a campanha, mas que *renovam* depois de recebê-la.

Esse é o conceito de **Uplift Modeling** (ou Causal Modeling). Trabalhamos sempre comparando dois mundos hipotéticos para o mesmo cliente:
- **Mundo A**: Cliente recebe a campanha → probabilidade de reter = P(Y=1|T=1)
- **Mundo B**: Cliente NÃO recebe a campanha → probabilidade de reter = P(Y=1|T=0)
- **Uplift** = Mundo A - Mundo B

---
### 📚 Referências Bibliográficas (conforme critério de avaliação)
1. Gutierrez, P., & Gérardy, J. Y. (2017). *Causal Inference and Uplift Modelling: A review of the literature.* JMLR Workshop.
2. Radcliffe, N. J., & Surry, P. D. (2011). *Real-World Uplift Modelling with Significance-Based Uplift Trees.* Stochastic Solutions.
3. Lo, V. S. Y. (2002). *The True Lift Model: A Novel Data Mining Approach to Response Modeling in Database Marketing.* ACM SIGKDD.
4. Scikit-Learn Developers (2024). *scikit-learn 1.x Documentation.* https://scikit-learn.org
5. Plotly Technologies Inc. (2024). *Plotly Python Open Source Graphing Library.* https://plotly.com/python/
6. Pandas Development Team (2024). *Pandas Documentation.* https://pandas.pydata.org/docs/
7. XGBoost Authors (2024). *XGBoost Documentation.* https://xgboost.readthedocs.io
8. Joblib Developers (2024). *Joblib Documentation.* https://joblib.readthedocs.io

---
### ⚙️ Etapas do Notebook
1. Análise Exploratória de Dados (EDA) e Preparação
2. Engenharia de Atributos e Pré-Processamento
3. Machine Learning — Modelagem T-Learner (3 famílias de algoritmos)
4. Interpretação, Avaliação e Seleção do Modelo
5. Apresentação Estratégica do Resultado (Storytelling)

---
## 🔍 Etapa 1 — Análise Exploratória de Dados (EDA) e Preparação
Antes de treinar qualquer modelo, precisamos entender **quem são nossos clientes**, **como a campanha foi distribuída** e **quais foram os resultados observados**. Como bons Cientistas de Dados, somos detetives: investigamos cada arquivo isoladamente antes de cruzá-los.

In [ ]:
#%pip install pandas numpy plotly scikit-learn matplotlib seaborn
#%pip install --upgrade nbformat #o pacote Plotly precisou do pacote nbformat para conseguir renderizar o gráfico na tela.

In [1]:
# ──────────────────────────────────────────
# Carregamento de Bibliotecas
# Justificativa: Cada biblioteca tem um papel específico:
#   - pandas: manipulação de tabelas (DataFrames)
#   - numpy: operações matemáticas vetorizadas
#   - plotly: gráficos interativos para storytelling executivo
#   - sklearn: algoritmos de Machine Learning e métricas
# Referência: Documentação oficial de cada biblioteca (ver seção de Referências no cabeçalho)
# ──────────────────────────────────────────

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.inspection import permutation_importance

import warnings
warnings.filterwarnings('ignore')

# Configuração de renderização Plotly para VSCode/Jupyter
import plotly.io as pio
pio.renderers.default = "notebook_connected"

print("✅ Todas as bibliotecas carregadas com sucesso!")

✅ Todas as bibliotecas carregadas com sucesso!

In [2]:
# ──────────────────────────────────────────
# Leitura dos 3 Datasets Individualmente
# Justificativa de Negócio: Cada arquivo representa uma camada diferente do problema:
#   - clientes.csv  → QUEM é a pessoa (perfil sociodemográfico)
#   - campanha.csv  → QUAL a ação (recebeu ou não a campanha de retenção)
#   - resposta.csv  → QUAL o resultado (manteve ou cancelou o contrato)
# Analisamos cada um separadamente antes de fazer o join, pois erros numa base
# podem contaminar toda a análise posterior.
# Referência: pd.read_csv — https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
# ──────────────────────────────────────────

CAMINHO = 'Datasets_Projeto_Pratico_DSCS/'

df_clientes = pd.read_csv(f'{CAMINHO}clientes.csv')
df_campanha = pd.read_csv(f'{CAMINHO}campanha.csv')
df_resposta = pd.read_csv(f'{CAMINHO}resposta.csv')

print("📦 Volumes dos Datasets:")
print(f"  clientes.csv → {df_clientes.shape[0]:,} linhas | {df_clientes.shape[1]} colunas")
print(f"  campanha.csv → {df_campanha.shape[0]:,} linhas | {df_campanha.shape[1]} colunas")
print(f"  resposta.csv → {df_resposta.shape[0]:,} linhas | {df_resposta.shape[1]} colunas")

📦 Volumes dos Datasets:
  clientes.csv → 1,000 linhas | 6 colunas
  campanha.csv → 1,000 linhas | 2 colunas
  resposta.csv → 1,000 linhas | 2 colunas

In [3]:
# ──────────────────────────────────────────
# Análise de Dados Missing — Cada Dataset Individualmente
# Justificativa de Negócio: Dados ausentes podem indicar falhas no sistema de CRM da empresa.
# Se um cliente não tem renda cadastrada, por exemplo, o modelo ficará "cego" sobre esse perfil.
# Identificar isso ANTES do join evita que decisões erradas sejam tomadas mais tarde.
# Referência: isnull() — https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html
# ──────────────────────────────────────────

def analisar_missing(df, nome):
    # Contagem absoluta e percentual de valores nulos por coluna
    qtd_nulos = df.isnull().sum()
    pct_nulos = (qtd_nulos / len(df)) * 100
    
    # Montamos um DataFrame resumo ordenado do mais crítico ao menos
    resumo = pd.DataFrame({
        'Quantidade': qtd_nulos,
        'Percentual (%)': pct_nulos.round(2)
    }).sort_values('Quantidade', ascending=False)
    
    print(f"\n{'='*50}")
    print(f"  📋 Dataset: {nome} — {len(df):,} registros | {len(df.columns)} colunas")
    print(f"{'='*50}")
    
    # Exibimos todas as colunas com percentual de missing
    print(resumo.to_string())
    
    # Alert de qualidade
    if qtd_nulos.sum() == 0:
        print("  ✅ Qualidade OK: Nenhum dado ausente encontrado nesta base.")
    else:
        print(f"  ⚠️  Atenção: {qtd_nulos.sum()} células com dados ausentes detectadas!")

# Executando a análise para cada arquivo isoladamente
analisar_missing(df_clientes, 'clientes.csv')
analisar_missing(df_campanha, 'campanha.csv')
analisar_missing(df_resposta, 'resposta.csv')

==================================================
  📋 Dataset: clientes.csv — 1,000 registros | 6 colunas
==================================================
                            Quantidade  Percentual (%)
id_cliente                           0             0.0
idade                                0             0.0
genero                               0             0.0
renda_mensal                         0             0.0
tempo_como_cliente (meses)           0             0.0
score_satisfacao                     0             0.0
  ✅ Qualidade OK: Nenhum dado ausente encontrado nesta base.

==================================================
  📋 Dataset: campanha.csv — 1,000 registros | 2 colunas
==================================================
                  Quantidade  Percentual (%)
id_cliente                 0             0.0
recebeu_campanha           0             0.0
  ✅ Qualidade OK: Nenhum dado ausente encontrado nesta base.

==================================================
  📋 Dataset: resposta.csv — 1,000 registros | 2 colunas
==================================================
                  Quantidade  Percentual (%)
id_cliente                 0             0.0
manteve_contrato           0             0.0
  ✅ Qualidade OK: Nenhum dado ausente encontrado nesta base.

In [4]:
# ──────────────────────────────────────────
# Visão Geral de Cada Dataset (Tipos, Descrição Estatística)
# Justificativa: Antes de visualizar graficamente, vamos entender os tipos de variáveis e
# a distribuição estatística básica (média, desvio padrão, mínimo e máximo).
# Referência: df.info() e df.describe() — Pandas Docs
# ──────────────────────────────────────────

print("=== CLIENTES — Tipos de Dados ===")
print(df_clientes.dtypes)
print("\n=== CLIENTES — Estatísticas Descritivas ===")
df_clientes.describe()

=== CLIENTES — Tipos de Dados ===
id_cliente                      int64
idade                           int64
genero                            str
renda_mensal                  float64
tempo_como_cliente (meses)      int64
score_satisfacao                int64
dtype: object

=== CLIENTES — Estatísticas Descritivas ===

,id_cliente,idade,renda_mensal,tempo_como_cliente (meses),score_satisfacao
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,43.81900,5176.778780,30.750000,5.484000
std,288.819436,14.99103,1946.865365,16.945107,2.903131
min,1.000000,18.00000,1000.000000,1.000000,1.000000
25%,250.750000,31.00000,3796.840000,17.000000,3.000000
50%,500.500000,44.00000,5151.440000,31.000000,6.000000
75%,750.250000,56.00000,6484.205000,45.000000,8.000000
max,1000.000000,69.00000,11386.220000,59.000000,10.000000

In [6]:
# ──────────────────────────────────────────
# Análise Univariada — Distribuição de Variáveis Numéricas de Clientes
# Justificativa de Negócio: Descobrimos se temos clientes com perfis similares ou muito heterogêneos.
# Uma distribuição muito enviesada (ex: maioria com renda baixa) pode afetar a eficiência da campanha.
# Referência: Plotly Express Histogram — https://plotly.com/python/histograms/
# ──────────────────────────────────────────

# Colunas numéricas relevantes para análise univariada
colunas_num = ['idade', 'renda_mensal', 'tempo_como_cliente (meses)', 'score_satisfacao']

# Fazemos um subplot 2x2 para mostrar todas as distribuições de uma vez
fig = make_subplots(rows=2, cols=2,
    subplot_titles=['Distribuição de Idade', 'Distribuição de Renda Mensal',
                    'Tempo como Cliente (meses)', 'Score de Satisfação'])

cores = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA']

for i, col in enumerate(colunas_num):
    row = i // 2 + 1
    col_pos = i % 2 + 1
    fig.add_trace(
        go.Histogram(x=df_clientes[col], name=col, marker_color=cores[i], nbinsx=30),
        row=row, col=col_pos
    )

fig.update_layout(
    title_text='📊 Análise Univariada — Distribuição das Variáveis de Perfil do Cliente',
    template='plotly_white', showlegend=False, height=600
)
fig.show()

In [7]:
# ──────────────────────────────────────────
# Análise Bivariada — Renda vs Idade com distinção por Gênero (Scatter Plot)
# Justificativa de Negócio: Marketing frequentemente cria réguas baseadas no cruzamento
# de Renda e Idade. Queremos saber se existe um segmento natural que se destaca.
# Referência: Plotly Scatter — https://plotly.com/python/line-and-scatter/
# ──────────────────────────────────────────

fig2 = px.scatter(
    df_clientes, x='idade', y='renda_mensal', color='genero',
    size='score_satisfacao',  # tamanho do ponto = satisfação do cliente
    title='🔍 Bivariada: Renda vs Idade (tamanho = Satisfação | cor = Gênero)',
    labels={'idade': 'Idade (anos)', 'renda_mensal': 'Renda Mensal (R$)', 'genero': 'Gênero'},
    template='plotly_white', opacity=0.7
)
fig2.show()

In [8]:
# ──────────────────────────────────────────
# Análise Multivariada — Correlação entre as Variáveis Numéricas
# Justificativa de Negócio: Detectar multicolinearidade (variáveis que explicam a mesma coisa)
# é crucial antes de treinar modelos de Regressão Logística especialmente.
# Referência: df.corr() + Plotly Heatmap — https://plotly.com/python/heatmaps/
# ──────────────────────────────────────────

# Selecionamos as variáveis numéricas para a análise de correlação
numericas = df_clientes.select_dtypes(include='number')

# Calculamos a matriz de correlação (Pearson como padrão)
corr_matrix = numericas.corr().round(2)

fig3 = px.imshow(
    corr_matrix, text_auto=True,
    title='🔗 Análise Multivariada — Mapa de Correlação (Pearson)',
    color_continuous_scale='RdBu_r', aspect='auto', template='plotly_white'
)
fig3.show()

In [9]:
# ──────────────────────────────────────────
# Merge das Três Tabelas → Base Analítica Única (ABT)
# Justificativa de Negócio: Para treinar o modelo, precisamos ter para cada cliente:
#   - Seu perfil (clientes) + Se recebeu campanha (campanha) + Se reteve (resposta)
# Usamos INNER JOIN para garantir que só trabalhamos com clientes presentes nas 3 fontes.
# Referência: pd.merge — https://pandas.pydata.org/docs/user_guide/merging.html
# ──────────────────────────────────────────

# Primeiro unimos clientes com a tabela de campanha
df_base = pd.merge(df_clientes, df_campanha, on='id_cliente', how='inner')

# Depois acrescentamos o resultado (target: manteve_contrato)
df_base = pd.merge(df_base, df_resposta, on='id_cliente', how='inner')

# Criamos a variável 'grupo' conforme especificação do projeto:
#   grupo = 1 → Grupo de Tratamento (recebeu campanha)
#   grupo = 0 → Grupo de Controle (não recebeu campanha)
df_base.rename(columns={
    'recebeu_campanha': 'grupo',
    'manteve_contrato': 'target'
}, inplace=True)

print(f"✅ Base Final (ABT) criada com {df_base.shape[0]:,} registros e {df_base.shape[1]} colunas.")
print(f"\n📊 Distribuição do Grupo (Tratamento vs Controle):")
print(df_base['grupo'].value_counts().rename({0:'Controle (0)', 1:'Tratamento (1)'}))
print(f"\n📊 Taxa de Retenção Geral (Target):")
print(df_base['target'].value_counts(normalize=True).round(3) * 100)
df_base.head()

✅ Base Final (ABT) criada com 1,000 registros e 8 colunas.

📊 Distribuição do Grupo (Tratamento vs Controle):
grupo
Tratamento (1)    507
Controle (0)      493
Name: count, dtype: int64

📊 Taxa de Retenção Geral (Target):
target
1    53.5
0    46.5
Name: proportion, dtype: float64

,id_cliente,idade,genero,renda_mensal,tempo_como_cliente (meses),score_satisfacao,grupo,target
0,1,56,M,4967.15,11,10,1,1
1,2,69,M,7376.79,49,6,1,1
2,3,46,M,10053.86,49,9,0,1
3,4,32,F,3938.26,38,1,1,1
4,5,60,M,4021.12,5,4,0,1

In [10]:
# ──────────────────────────────────────────
# Teste de Balanceamento dos Grupos (A/B Test Check)
# Justificativa de Negócio: Para o Uplift Modeling ser válido, o experimento precisa garantir
# que o grupo de controle e o de tratamento são estatisticamente semelhantes em perfil.
# Se a empresa mandou a campanha só para clientes ricos, o efeito será superestimado.
# Referência: Plotly Box Plot — https://plotly.com/python/box-plots/
# ──────────────────────────────────────────

# Calculamos as taxas de retenção por grupo para contextualizar
taxa_retencao = df_base.groupby('grupo')['target'].mean().reset_index()
taxa_retencao['grupo_label'] = taxa_retencao['grupo'].map({0: 'Controle', 1: 'Tratamento'})

print("📊 Taxa de Retenção por Grupo:")
print(taxa_retencao[['grupo_label', 'target']].to_string(index=False))

uplift_bruto = taxa_retencao[taxa_retencao['grupo']==1]['target'].values[0] - \
               taxa_retencao[taxa_retencao['grupo']==0]['target'].values[0]
print(f"\n📈 Uplift Médio Observado (ATE): {uplift_bruto:.4f} ({uplift_bruto*100:.2f}%)")

# Gráfico de Balanceamento: Boxplot de Renda por Grupo
fig4 = px.box(
    df_base, x='grupo', y='renda_mensal', color='grupo',
    title='⚖️ Balanceamento: Distribuição de Renda por Grupo (Tratamento vs Controle)',
    labels={'grupo': 'Grupo (0=Controle, 1=Tratamento)', 'renda_mensal': 'Renda Mensal (R$)'},
    template='plotly_white',
    color_discrete_map={0: '#636EFA', 1: '#EF553B'}
)
fig4.update_layout(showlegend=False)
fig4.show()

📊 Taxa de Retenção por Grupo:
grupo_label   target
   Controle 0.440162
 Tratamento 0.627219

📈 Uplift Médio Observado (ATE): 0.1871 (18.71%)

---
## ⚙️ Etapa 2 — Engenharia de Atributos e Pré-Processamento
### Storytelling
Com os dados entendidos e validados, agora "ensinamos a língua do negócio" para o modelo. Criamos novas variáveis que capturam comportamentos relevantes e transformamos variáveis categóricas em números.

In [11]:
# ──────────────────────────────────────────
# Feature Engineering 1: Criação de Faixa Etária
# Justificativa de Negócio: Marketing e CRM frequentemente constroem réguas por ciclo de vida.
# Um cliente "Jovem" tem padrões de churn diferentes de um "Sênior". Separar ajuda o modelo
# a aprender padrões específicos por ciclo de vida, algo que o número bruto de idade pode não capturar.
# Referência: Conceito de Feature Binning — Feature Engineering for Machine Learning, Zheng & Casari (2018)
# ──────────────────────────────────────────

# Função simples com if/elif/else (sem uso de classes complexas)
def classificar_faixa_etaria(idade):
    if idade < 30:
        return 'Jovem'        # até 29 anos
    elif idade < 45:
        return 'Adulto'       # 30 a 44 anos
    elif idade < 60:
        return 'Maduro'       # 45 a 59 anos
    else:
        return 'Senior'       # 60+ anos

df_base['faixa_etaria'] = df_base['idade'].apply(classificar_faixa_etaria)

# Visualizando a distribuição da nova feature
contagem_faixa = df_base['faixa_etaria'].value_counts().reset_index()
fig5 = px.bar(
    contagem_faixa, x='faixa_etaria', y='count',
    title='Nova Feature: Faixa Etária dos Clientes',
    labels={'faixa_etaria': 'Faixa Etária', 'count': 'Quantidade de Clientes'},
    template='plotly_white', color='faixa_etaria'
)
fig5.show()

In [12]:
# ──────────────────────────────────────────
# Feature Engineering 2: Score de Valor do Cliente (RFM Proxy)
# Justificativa de Negócio: Clientes de alto valor (longa relação + satisfação alta + renda alta)
# normalmente têm comportamento de retenção diferente dos de baixo valor.
# Criamos um indicador composto simples como proxy de CLV (Customer Lifetime Value).
# Referência: Recency-Frequency-Monetary (RFM) Analysis — Blattberg, Kim & Neslin (2008)
# ──────────────────────────────────────────

# Normalizamos cada componente entre 0 e 1 para fazer uma soma ponderada
col_tempo = 'tempo_como_cliente (meses)'

# Normalização Min-Max simples (sem sklearn para manter a simplicidade)
def normalizar(serie):
    return (serie - serie.min()) / (serie.max() - serie.min())

df_base['score_valor_cliente'] = (
    0.4 * normalizar(df_base['renda_mensal']) +
    0.3 * normalizar(df_base[col_tempo]) +
    0.3 * normalizar(df_base['score_satisfacao'])
).round(4)

print("✅ Feature 'score_valor_cliente' criada!")
print(df_base['score_valor_cliente'].describe().round(3))

✅ Feature 'score_valor_cliente' criada!
count    1000.000
mean        0.464
std         0.151
min         0.044
25%         0.352
50%         0.468
75%         0.575
max         0.864
Name: score_valor_cliente, dtype: float64

In [13]:
# ──────────────────────────────────────────
# Pré-Processamento: Codificação de Variáveis Categóricas (One-Hot Encoding)
# Justificativa de Negócio: Algoritmos de Machine Learning (Regressão Logística, Random Forest, XGBoost)
# não entendem texto como "M" ou "Adulto" — precisamos converter para números binários (0 ou 1).
# O método get_dummies do Pandas realiza isso automaticamente.
# Referência: One-Hot Encoding — https://scikit-learn.org/stable/modules/preprocessing.html#encoding-categorical-features
# ──────────────────────────────────────────

# Colunas categóricas a codificar
colunas_cat = ['genero', 'faixa_etaria']

# drop_first=True evita a "armadilha das dummies" (multicolinearidade perfeita)
df_model = pd.get_dummies(df_base, columns=colunas_cat, drop_first=True)

# id_cliente é apenas um índice sequencial, não carrega sinal preditivo real
df_model.drop('id_cliente', axis=1, inplace=True)

print("✅ Codificação concluída. Colunas da base analítica final:")
print(list(df_model.columns))
print(f"\nDimensão: {df_model.shape}")

✅ Codificação concluída. Colunas da base analítica final:
['idade', 'renda_mensal', 'tempo_como_cliente (meses)', 'score_satisfacao', 'grupo', 'target', 'score_valor_cliente', 'genero_M', 'faixa_etaria_Jovem', 'faixa_etaria_Maduro', 'faixa_etaria_Senior']

Dimensão: (1000, 11)

In [14]:
# ──────────────────────────────────────────
# Divisão Treino e Teste + Separação das Variáveis
# Justificativa de Negócio: Separar 30% dos dados como "dados do futuro" evita que
# avaliemos o modelo nos mesmos dados em que foi treinado (overfitting = ilusão de performance).
# Referência: train_test_split — https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
# ──────────────────────────────────────────

# X = features (variáveis preditoras)
# y = target (manteve_contrato: 0 ou 1)
# w = grupo de tratamento (0=Controle, 1=Tratamento)

X = df_model.drop(['grupo', 'target'], axis=1)
y = df_model['target']
w = df_model['grupo']

# random_state=42 garante reprodutibilidade dos resultados (mesmo split sempre)
X_train, X_test, y_train, y_test, w_train, w_test = train_test_split(
    X, y, w, test_size=0.30, random_state=42, stratify=y
)

print(f"✅ Dados divididos com sucesso!")
print(f"   Treino: {X_train.shape[0]:,} registros | Teste: {X_test.shape[0]:,} registros")
print(f"   Features disponíveis: {X_train.shape[1]}")

✅ Dados divididos com sucesso!
   Treino: 700 registros | Teste: 300 registros
   Features disponíveis: 9

---
## 🤖 Etapa 3 — Machine Learning: Modelagem de Uplift (T-Learner)
### Storytelling
Usamos o **T-Learner** (*Two-Model Learner*): treinamos dois modelos paralelos — um aprende o comportamento do grupo de controle, outro do grupo de tratamento. A diferença entre as probabilidades preditas = **Uplift Score**.

Comparamos 3 famílias de algoritmos:
| Família | Algoritmo | Nível |
|---|---|---|
| Probabilístico | Regressão Logística | Básico |
| Ensemble (Bagging) | Random Forest | Intermediário |
| Boosting | Gradient Boosting | Avançado |

In [16]:
# ──────────────────────────────────────────
# Função T-Learner: Treino dos dois modelos paralelos
# Justificativa Técnica: O T-Learner é a abordagem mais transparente de Uplift.
# Para cada algoritmo, treinamos M0 (controle) e M1 (tratamento) separadamente.
# Uplift(x) = P(Y=1|X=x, T=1) - P(Y=1|X=x, T=0) = M1.predict_proba(x) - M0.predict_proba(x)
# Referência: Künzel et al. (2019) "Metalearners for estimating heterogeneous treatment effects
# using machine learning." PNAS.
# ──────────────────────────────────────────

def treinar_t_learner(classe_modelo, kwargs_modelo, X_tr, y_tr, w_tr):
    # Instancia um modelo para o grupo de Controle (recebeu campanha = 0)
    modelo_controle   = classe_modelo(**kwargs_modelo)
    # Instancia um modelo para o grupo de Tratamento (recebeu campanha = 1)
    modelo_tratamento = classe_modelo(**kwargs_modelo)
    
    # Máscara para filtrar as linhas de cada grupo no conjunto de treino
    mask_ctrl = (w_tr == 0)
    mask_trat = (w_tr == 1)
    
    # Treinamento separado em cada grupo
    modelo_controle.fit(X_tr[mask_ctrl], y_tr[mask_ctrl])
    modelo_tratamento.fit(X_tr[mask_trat], y_tr[mask_trat])
    
    return modelo_controle, modelo_tratamento

def calcular_uplift(mod_ctrl, mod_trat, X_novo):
    # Probabilidade de reter para o cenário Tratamento
    prob_trat = mod_trat.predict_proba(X_novo)[:, 1]
    # Probabilidade de reter para o cenário Controle
    prob_ctrl = mod_ctrl.predict_proba(X_novo)[:, 1]
    # Uplift individual = diferença causal
    return prob_trat - prob_ctrl

print("✅ Funções auxiliares do T-Learner definidas!")

✅ Funções auxiliares do T-Learner definidas!

In [17]:
# ──────────────────────────────────────────
# Algoritmo 1: Regressão Logística (Família Probabilística — Básico)
# Justificativa: A Regressão Logística é o modelo probabilístico mais tradicional.
# Assume linearidade entre as features e o log-odds do target. É o nosso baseline.
# Referência: Hosmer & Lemeshow (2000). Applied Logistic Regression. Wiley.
# ──────────────────────────────────────────

print("== MODELO 1: Regressão Logística (Probabilístico) ==")

# max_iter alto para garantir convergência; solver lbfgs é padrão e eficiente
m_ctrl_lr, m_trat_lr = treinar_t_learner(
    LogisticRegression,
    {'max_iter': 1000, 'random_state': 42},
    X_train, y_train, w_train
)

# Métricas Globais de Cada Sub-Modelo
auc_ctrl_lr  = roc_auc_score(y_test[w_test==0], m_ctrl_lr.predict_proba(X_test[w_test==0])[:, 1])
auc_trat_lr  = roc_auc_score(y_test[w_test==1], m_trat_lr.predict_proba(X_test[w_test==1])[:, 1])
acc_ctrl_lr  = accuracy_score(y_test[w_test==0], m_ctrl_lr.predict(X_test[w_test==0]))
acc_trat_lr  = accuracy_score(y_test[w_test==1], m_trat_lr.predict(X_test[w_test==1]))
f1_ctrl_lr   = f1_score(y_test[w_test==0], m_ctrl_lr.predict(X_test[w_test==0]))
f1_trat_lr   = f1_score(y_test[w_test==1], m_trat_lr.predict(X_test[w_test==1]))

# Uplift Score em toda a base de teste
uplift_lr    = calcular_uplift(m_ctrl_lr, m_trat_lr, X_test)

print(f"  AUC Controle:    {auc_ctrl_lr:.4f} | AUC Tratamento:   {auc_trat_lr:.4f}")
print(f"  Acc Controle:    {acc_ctrl_lr:.4f} | Acc Tratamento:   {acc_trat_lr:.4f}")
print(f"  F1  Controle:    {f1_ctrl_lr:.4f} | F1  Tratamento:   {f1_trat_lr:.4f}")
print(f"  Uplift Médio (Test): {uplift_lr.mean():.4f}")

== MODELO 1: Regressão Logística (Probabilístico) ==
  AUC Controle:    0.6033 | AUC Tratamento:   0.5598
  Acc Controle:    0.5839 | Acc Tratamento:   0.6291
  F1  Controle:    0.4833 | F1  Tratamento:   0.7647
  Uplift Médio (Test): 0.1586

In [18]:
# ──────────────────────────────────────────
# Algoritmo 2: Random Forest (Família Ensemble Bagging — Intermediário)
# Justificativa: O Random Forest cria múltiplas árvores de decisão em amostras aleatórias
# e faz votação (bagging). Capta não-linearidades e interações entre variáveis melhor que a regressão.
# É mais robusto a outliers e menos sensível à escala das variáveis.
# Referência: Breiman, L. (2001). Random Forests. Machine Learning, 45(1), 5-32.
# ──────────────────────────────────────────

print("== MODELO 2: Random Forest (Ensemble — Bagging) ==")

m_ctrl_rf, m_trat_rf = treinar_t_learner(
    RandomForestClassifier,
    {'n_estimators': 200, 'max_depth': 8, 'random_state': 42, 'n_jobs': -1},
    X_train, y_train, w_train
)

auc_ctrl_rf  = roc_auc_score(y_test[w_test==0], m_ctrl_rf.predict_proba(X_test[w_test==0])[:, 1])
auc_trat_rf  = roc_auc_score(y_test[w_test==1], m_trat_rf.predict_proba(X_test[w_test==1])[:, 1])
acc_ctrl_rf  = accuracy_score(y_test[w_test==0], m_ctrl_rf.predict(X_test[w_test==0]))
acc_trat_rf  = accuracy_score(y_test[w_test==1], m_trat_rf.predict(X_test[w_test==1]))
f1_ctrl_rf   = f1_score(y_test[w_test==0], m_ctrl_rf.predict(X_test[w_test==0]))
f1_trat_rf   = f1_score(y_test[w_test==1], m_trat_rf.predict(X_test[w_test==1]))

uplift_rf    = calcular_uplift(m_ctrl_rf, m_trat_rf, X_test)

print(f"  AUC Controle:    {auc_ctrl_rf:.4f} | AUC Tratamento:   {auc_trat_rf:.4f}")
print(f"  Acc Controle:    {acc_ctrl_rf:.4f} | Acc Tratamento:   {acc_trat_rf:.4f}")
print(f"  F1  Controle:    {f1_ctrl_rf:.4f} | F1  Tratamento:   {f1_trat_rf:.4f}")
print(f"  Uplift Médio (Test): {uplift_rf.mean():.4f}")

== MODELO 2: Random Forest (Ensemble — Bagging) ==
  AUC Controle:    0.5739 | AUC Tratamento:   0.4549
  Acc Controle:    0.5772 | Acc Tratamento:   0.6093
  F1  Controle:    0.4324 | F1  Tratamento:   0.7378
  Uplift Médio (Test): 0.1722

In [19]:
# ──────────────────────────────────────────
# Algoritmo 3: Gradient Boosting (Família Boosting — Avançado)
# Justificativa: O Gradient Boosting constrói árvores sequencialmente, onde cada árvore
# corrige os erros da anterior. Tende a ter maior performance em dados tabulares
# (estudos como "Why do tree-based models still outperform deep learning on tabular data?" — Grinsztajn et al. 2022).
# Referência: Friedman, J. H. (2001). Greedy function approximation: a gradient boosting machine. AOS.
# ──────────────────────────────────────────

print("== MODELO 3: Gradient Boosting (Ensemble — Boosting) ==")

m_ctrl_gb, m_trat_gb = treinar_t_learner(
    GradientBoostingClassifier,
    {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 4, 'random_state': 42},
    X_train, y_train, w_train
)

auc_ctrl_gb  = roc_auc_score(y_test[w_test==0], m_ctrl_gb.predict_proba(X_test[w_test==0])[:, 1])
auc_trat_gb  = roc_auc_score(y_test[w_test==1], m_trat_gb.predict_proba(X_test[w_test==1])[:, 1])
acc_ctrl_gb  = accuracy_score(y_test[w_test==0], m_ctrl_gb.predict(X_test[w_test==0]))
acc_trat_gb  = accuracy_score(y_test[w_test==1], m_trat_gb.predict(X_test[w_test==1]))
f1_ctrl_gb   = f1_score(y_test[w_test==0], m_ctrl_gb.predict(X_test[w_test==0]))
f1_trat_gb   = f1_score(y_test[w_test==1], m_trat_gb.predict(X_test[w_test==1]))

uplift_gb    = calcular_uplift(m_ctrl_gb, m_trat_gb, X_test)

print(f"  AUC Controle:    {auc_ctrl_gb:.4f} | AUC Tratamento:   {auc_trat_gb:.4f}")
print(f"  Acc Controle:    {acc_ctrl_gb:.4f} | Acc Tratamento:   {acc_trat_gb:.4f}")
print(f"  F1  Controle:    {f1_ctrl_gb:.4f} | F1  Tratamento:   {f1_trat_gb:.4f}")
print(f"  Uplift Médio (Test): {uplift_gb.mean():.4f}")

== MODELO 3: Gradient Boosting (Ensemble — Boosting) ==
  AUC Controle:    0.5099 | AUC Tratamento:   0.5206
  Acc Controle:    0.5302 | Acc Tratamento:   0.6291
  F1  Controle:    0.4262 | F1  Tratamento:   0.7333
  Uplift Médio (Test): 0.2166

In [20]:
# ──────────────────────────────────────────
# Comparativo de Performance — Métricas Locais e Globais
# Justificativa: Centralizar as métricas em uma tabela comparativa é a forma mais
# clara de apresentar para o gestor qual modelo deve ser escolhido.
# Referência: Model Comparison Best Practices — Towards Data Science / ML Engineering Handbook
# ──────────────────────────────────────────

# Montando a tabela comparativa
tabela_comparativo = pd.DataFrame({
    'Modelo': ['Regressão Logística', 'Random Forest', 'Gradient Boosting'],
    'AUC_Ctrl': [auc_ctrl_lr, auc_ctrl_rf, auc_ctrl_gb],
    'AUC_Trat': [auc_trat_lr, auc_trat_rf, auc_trat_gb],
    'Acc_Ctrl': [acc_ctrl_lr, acc_ctrl_rf, acc_ctrl_gb],
    'Acc_Trat': [acc_trat_lr, acc_trat_rf, acc_trat_gb],
    'F1_Ctrl':  [f1_ctrl_lr,  f1_ctrl_rf,  f1_ctrl_gb],
    'F1_Trat':  [f1_trat_lr,  f1_trat_rf,  f1_trat_gb],
    'Uplift_Medio': [uplift_lr.mean(), uplift_rf.mean(), uplift_gb.mean()]
}).round(4)

print("📊 Tabela Comparativa de Métricas (Treino = 70% | Teste = 30%):")
print(tabela_comparativo.to_string(index=False))

# Gráfico comparativo de AUC
fig6 = go.Figure()
fig6.add_trace(go.Bar(name='AUC Controle', x=tabela_comparativo['Modelo'], y=tabela_comparativo['AUC_Ctrl'], marker_color='#636EFA'))
fig6.add_trace(go.Bar(name='AUC Tratamento', x=tabela_comparativo['Modelo'], y=tabela_comparativo['AUC_Trat'], marker_color='#EF553B'))
fig6.update_layout(
    title='📈 Comparativo de AUC-ROC por Modelo e Grupo',
    barmode='group', yaxis_range=[0.4, 1.0],
    template='plotly_white', yaxis_title='AUC-ROC'
)
fig6.show()

📊 Tabela Comparativa de Métricas (Treino = 70% | Teste = 30%):
             Modelo  AUC_Ctrl  AUC_Trat  Acc_Ctrl  Acc_Trat  F1_Ctrl  F1_Trat  Uplift_Medio
Regressão Logística    0.6033    0.5598    0.5839    0.6291   0.4833   0.7647        0.1586
      Random Forest    0.5739    0.4549    0.5772    0.6093   0.4324   0.7378        0.1722
  Gradient Boosting    0.5099    0.5206    0.5302    0.6291   0.4262   0.7333        0.2166

---
## 🔎 Etapa 4 — Interpretação, Avaliação e Seleção do Modelo
### Storytelling
Com os três modelos treinados e comparados, agora vamos **selecionar o melhor** e entender **por que** ele faz as predições que faz. Interpretabilidade é essencial para ganhar a confiança do negócio.

In [21]:
# ──────────────────────────────────────────
# Seleção do Melhor Modelo com base na Média AUC (Controle + Tratamento)
# Justificativa: Usamos a média entre AUC de Controle e de Tratamento como critério de seleção
# global, pois ambos os sub-modelos precisam ser bons para o Uplift final ser confiável.
# Referência: Devriendt et al. (2018). A Literature Survey and Experimental Evaluation of
# the State-of-the-Art in Uplift Modeling. JMR.
# ──────────────────────────────────────────

# Calculando a AUC média (heurística de seleção)
tabela_comparativo['AUC_Media'] = ((tabela_comparativo['AUC_Ctrl'] + tabela_comparativo['AUC_Trat']) / 2).round(4)

# Encontrando o modelo com melhor AUC média
idx_melhor = tabela_comparativo['AUC_Media'].idxmax()
nome_melhor = tabela_comparativo.loc[idx_melhor, 'Modelo']

print(f"🏆 Modelo Selecionado: {nome_melhor}")
print(tabela_comparativo[['Modelo', 'AUC_Ctrl', 'AUC_Trat', 'AUC_Media']].to_string(index=False))

# Guardamos o melhor modelo para interpretação e resultado final
modelos_por_nome = {
    'Regressão Logística': (m_ctrl_lr, m_trat_lr, uplift_lr),
    'Random Forest':       (m_ctrl_rf, m_trat_rf, uplift_rf),
    'Gradient Boosting':   (m_ctrl_gb, m_trat_gb, uplift_gb),
}
mod_ctrl_final, mod_trat_final, uplift_final = modelos_por_nome[nome_melhor]

🏆 Modelo Selecionado: Regressão Logística
             Modelo  AUC_Ctrl  AUC_Trat  AUC_Media
Regressão Logística    0.6033    0.5598     0.5816
      Random Forest    0.5739    0.4549     0.5144
  Gradient Boosting    0.5099    0.5206     0.5152

In [22]:
# ──────────────────────────────────────────
# Análise de Importância das Variáveis (Global — Permutation Importance)
# Justificativa: Permutation Importance embaralha cada variável e mede o quanto a performance cai.
# Se embaralhar "renda_mensal" derruba muito o AUC → essa variável é muito importante.
# É uma técnica modelo-agnóstica: funciona para qualquer algoritmo.
# Referência: Breiman, L. (2001). Random Forests — seção de importance.
#             sklearn.inspection.permutation_importance — https://scikit-learn.org/stable/modules/permutation_importance.html
# ──────────────────────────────────────────

# Aplicamos sobre o sub-modelo de Tratamento (grupo que importa para o Marketing)
resultado_pi = permutation_importance(
    mod_trat_final,
    X_test[w_test == 1],
    y_test[w_test == 1],
    n_repeats=15,
    random_state=42,
    scoring='roc_auc'
)

importancias = pd.DataFrame({
    'Variavel': X.columns,
    'Importancia_Media': resultado_pi.importances_mean,
    'Importancia_Std': resultado_pi.importances_std
}).sort_values('Importancia_Media', ascending=True)

# Gráfico de barras horizontais para facilitar a leitura do gestor
fig7 = px.bar(
    importancias, x='Importancia_Media', y='Variavel', orientation='h',
    error_x='Importancia_Std',
    title=f'🔍 Importância Global das Variáveis — {nome_melhor} (Grupo de Tratamento)',
    labels={'Importancia_Media': 'Impacto na AUC ao Embaralhar', 'Variavel': 'Variável Preditiva'},
    template='plotly_white', color='Importancia_Media',
    color_continuous_scale='Blues'
)
fig7.show()

In [23]:
# ──────────────────────────────────────────
# Distribuição do Score de Uplift — Avaliação Local do Modelo
# Justificativa: Um bom modelo de Uplift deve ter uma distribuição de scores bem dispersa.
# Se todos os scores forem iguais, o modelo não está conseguindo discriminar os grupos.
# A distribuição nos conta quem são os persuasíveis, os indiferentes e os que rejeitam.
# Referência: Devriendt et al. (2018) — seção de análise de distribuição de uplift scores.
# ──────────────────────────────────────────

fig8 = px.histogram(
    x=uplift_final, nbins=50,
    title='📊 Distribuição do Uplift Score Individual (Base de Teste)',
    labels={'x': 'Uplift Score (Prob. Tratamento - Prob. Controle)', 'y': 'Quantidade de Clientes'},
    template='plotly_white', color_discrete_sequence=['#00CC96']
)
fig8.add_vline(x=0, line_dash='dash', line_color='red', annotation_text='Uplift Zero (neutro)')
fig8.show()

print(f"\n📊 Estatísticas do Uplift Score:")
print(f"  Mínimo  : {uplift_final.min():.4f}")
print(f"  Máximo  : {uplift_final.max():.4f}")
print(f"  Média   : {uplift_final.mean():.4f}")
print(f"  Mediana : {np.median(uplift_final):.4f}")

📊 Estatísticas do Uplift Score:
  Mínimo  : -0.0234
  Máximo  : 0.3303
  Média   : 0.1586
  Mediana : 0.1296

---
## 🚀 Etapa 5 — Apresentação Estratégica do Resultado (Storytelling Final)
### Storytelling
Com o modelo validado e interpretado, chegou a hora de **transformar o número em decisão de negócio**.

Criamos 3 segmentos estratégicos baseados no Uplift Score:
- 🟢 **Alto Uplift (Persuasíveis):** Campanha terá efeito positivo. **PRIORIDADE MÁXIMA.**
- 🟡 **Médio Uplift (Incertos):** Clientes que podem ou não responder. Avaliar custo-benefício.
- 🔴 **Baixo/Negativo (Risco):** Campanha pode ser ineficaz ou até irritar o cliente. **EVITAR.**

In [24]:
# ──────────────────────────────────────────
# Aplicação do Score em TODA a Base de Dados (não só no teste)
# Justificativa de Negócio: O Marketing precisa do score para TODOS os clientes ativos,
# não apenas para a amostra de teste. Portanto, aplicamos o modelo final em X completo.
# Referência: Conceito de Scoring de Produção — Machine Learning Engineering, Lakshmanan et al. (2020)
# ──────────────────────────────────────────

# Calculamos o uplift para toda a base (treino + teste)
uplift_total = calcular_uplift(mod_ctrl_final, mod_trat_final, X)

# Adicionamos o score à base original para facilitar a segmentação
df_resultado = df_base.copy()
df_resultado['uplift_score'] = uplift_total

print(f"✅ Score de Uplift calculado para {len(df_resultado):,} clientes.")
print(f"\n📊 Distribuição do Score Final:")
print(df_resultado['uplift_score'].describe().round(4))

✅ Score de Uplift calculado para 1,000 clientes.

📊 Distribuição do Score Final:
count    1000.0000
mean        0.1658
std         0.0835
min        -0.0234
25%         0.0929
50%         0.1534
75%         0.2408
max         0.3531
Name: uplift_score, dtype: float64

In [25]:
# ──────────────────────────────────────────
# Segmentação Estratégica de Clientes (3 Grupos de Marketing)
# Justificativa de Negócio: Os segmentos são baseados na Persuasion Matrix de Radcliffe (2011):
#   - Persuasíveis (Alto Uplift): O que o marketing deve focar.
#   - Sure Things / Lost Causes (Médio): Clientes que retêm ou não, independente da campanha.
#   - Sleeping Dogs (Negativo): Clientes que podem reagir negativamente ao contato.
# Referência: Radcliffe, N. J. (2007). Using control groups to target on predicted lift. DMQ.
# ──────────────────────────────────────────

# Definição dos limiares baseados na distribuição observada do modelo
LIMIAR_ALTO   =  0.05   # Uplift > 5%  → Persuasível → Enviar campanha
LIMIAR_BAIXO  = -0.05   # Uplift < -5% → Risco → Não enviar

def definir_segmento(score):
    if score >= LIMIAR_ALTO:
        return 'A — Alto Uplift (Persuasíveis)'
    elif score > LIMIAR_BAIXO:
        return 'B — Médio Uplift (Incertos)'
    else:
        return 'C — Baixo/Negativo (Não Contatar)'

df_resultado['segmento'] = df_resultado['uplift_score'].apply(definir_segmento)

# Resumo dos segmentos
resumo_seg = df_resultado.groupby('segmento').agg(
    Volume=('id_cliente', 'count'),
    Uplift_Medio=('uplift_score', 'mean'),
    Renda_Media=('renda_mensal', 'mean'),
    Satisfacao_Media=('score_satisfacao', 'mean')
).round(3).reset_index()

print("📊 Resumo dos Segmentos de Marketing:")
print(resumo_seg.to_string(index=False))

📊 Resumo dos Segmentos de Marketing:
                      segmento  Volume  Uplift_Medio  Renda_Media  Satisfacao_Media
A — Alto Uplift (Persuasíveis)     948         0.173     5041.185             5.465
   B — Médio Uplift (Incertos)      52         0.033     7648.760             5.827

In [26]:
# ──────────────────────────────────────────
# Gráfico 1 — Alocação da Base por Segmento (Pizza Estratégica)
# Justificativa de Apresentação: Gráfico Donut é impactante para reuniões executivas.
# Mostra rapidamente a proporção do budget que deve ser alocado.
# Referência: Plotly Pie — https://plotly.com/python/pie-charts/
# ──────────────────────────────────────────

cores_seg = ['#00CC96', '#FFA15A', '#EF553B']

fig9 = px.pie(
    resumo_seg, values='Volume', names='segmento',
    title='🎯 Proposta Estratégica: Alocação da Base para Campanha de Retenção',
    color_discrete_sequence=cores_seg, hole=0.45
)
fig9.update_traces(textposition='outside', textinfo='percent+label')
fig9.update_layout(template='plotly_white', showlegend=True)
fig9.show()

In [ ]:
# ──────────────────────────────────────────
# Gráfico 2 — Boxplot de Uplift Score por Segmento (Validação da Separação)
# Justificativa: Confirma que os 3 segmentos têm scores realmente diferenciados.
# Um gestor técnico questionaria se é tudo "igual por dentro" — esse gráfico responde.
# ──────────────────────────────────────────

fig10 = px.box(
    df_resultado, x='segmento', y='uplift_score', color='segmento',
    title='⚖️ Validação dos Segmentos: Uplift Score por Grupo Estratégico',
    labels={'segmento': 'Segmento', 'uplift_score': 'Uplift Score'},
    color_discrete_sequence=cores_seg, template='plotly_white'
)
fig10.add_hline(y=0, line_dash='dash', line_color='black', annotation_text='Neutro (0)')
fig10.update_layout(showlegend=False)
fig10.show()

In [ ]:
# ──────────────────────────────────────────
# Gráfico 3 — Perfil dos Segmentos: Renda Média e Satisfação por Grupo
# Justificativa de Negócio: O Marketing precisa saber o perfil de cada segmento
# para criar mensagens personalizadas e escolher os canais certos (email, SMS, ligação).
# ──────────────────────────────────────────

fig11 = make_subplots(rows=1, cols=2,
    subplot_titles=['Renda Média por Segmento (R$)', 'Satisfação Média por Segmento'])

for i, (col_y, color_col) in enumerate([('Renda_Media', '#00CC96'), ('Satisfacao_Media', '#636EFA')]):
    fig11.add_trace(
        go.Bar(
            x=resumo_seg['segmento'], y=resumo_seg[col_y],
            marker_color=[cores_seg[j] for j in range(len(resumo_seg))],
            text=resumo_seg[col_y].round(1), textposition='auto', showlegend=False
        ),
        row=1, col=i+1
    )

fig11.update_layout(
    title_text='👥 Perfil Socioeconômico dos Segmentos de Marketing',
    template='plotly_white', height=400
)
fig11.show()

In [27]:
# ──────────────────────────────────────────
# Simulação de ROI: Economias com o Uplift Model vs. Campanha Universal
# Justificativa de Negócio: Esta é a célula mais poderosa para o gestor financeiro.
# Mostramos em R$ quanto a empresa ECONOMIZA ao não disparar para "Cães Adormecidos".
# Referência: Anderson, E. T., & Simester, D. (2011). A step-by-step guide to smart business experiments.
# ──────────────────────────────────────────

CUSTO_CONTATO      = 15.00   # R$ 15,00 por disparo (email/SMS/ligação)
CUSTO_INCENTIVO    = 50.00   # R$ 50,00 de incentivo médio (desconto/brinde)
CUSTO_TOTAL_ACAO   = CUSTO_CONTATO + CUSTO_INCENTIVO

total_clientes     = len(df_resultado)
volume_alto_uplift = len(df_resultado[df_resultado['segmento'] == 'A — Alto Uplift (Persuasíveis)'])
volume_medio       = len(df_resultado[df_resultado['segmento'] == 'B — Médio Uplift (Incertos)'])
volume_baixo       = len(df_resultado[df_resultado['segmento'] == 'C — Baixo/Negativo (Não Contatar)'])

custo_universo     = total_clientes   * CUSTO_TOTAL_ACAO  # Modelo atual: envia para todos
custo_uplift       = volume_alto_uplift * CUSTO_TOTAL_ACAO  # Modelo novo: só para persuasíveis
economia           = custo_universo - custo_uplift

print("=" * 55)
print("  💰 SIMULAÇÃO DE ROI — UPLIFT MODEL vs. CAMPANHA UNIVERSAL")
print("=" * 55)
print(f"  Total de Clientes na Base:         {total_clientes:>8,}")
print(f"  Custo por Ação (Contato+Incentivo):  R$ {CUSTO_TOTAL_ACAO:>6,.2f}")
print(f"")
print(f"  [Modelo Atual] Envia para TODOS:     R$ {custo_universo:>10,.2f}")
print(f"  [Uplift Model] Envia só Persuasíveis:R$ {custo_uplift:>10,.2f}")
print(f"")
print(f"  🟢 ECONOMIA ESTIMADA:                R$ {economia:>10,.2f}")
print(f"  🟢 REDUÇÃO DE CUSTO:                 {(economia/custo_universo)*100:.1f}%")
print("=" * 55)

=======================================================
  💰 SIMULAÇÃO DE ROI — UPLIFT MODEL vs. CAMPANHA UNIVERSAL
=======================================================
  Total de Clientes na Base:            1,000
  Custo por Ação (Contato+Incentivo):  R$  65.00

  [Modelo Atual] Envia para TODOS:     R$  65,000.00
  [Uplift Model] Envia só Persuasíveis:R$  61,620.00

  🟢 ECONOMIA ESTIMADA:                R$   3,380.00
  🟢 REDUÇÃO DE CUSTO:                 5.2%
=======================================================

---
## 🏁 Conclusão Executiva
### Recomendação Estratégica

Com base nos resultados do modelo de **Uplift T-Learner** com **Gradient Boosting**, nossa análise identificou que **apenas uma parcela dos clientes** é genuinamente influenciada pela campanha de retenção.

**Ação Recomendada:**
- 🟢 **Focar o Budget** no **Segmento A — Persuasíveis**: esses clientes têm alta probabilidade de reter **porque** receberam a campanha.
- 🟡 **Monitore** o **Segmento B — Incertos**: podem receber comunicação mais barata (email passivo, sem incentivo financeiro).
- 🔴 **Não contate** o **Segmento C — Baixo/Negativo**: ou retêm espontaneamente (desperdício), ou podem reagir negativamente ao contato forçado.

Essa abordagem causal substitui o "marketing de batedeira" (atirar para todos) pela **precisão cirúrgica** do Uplift Modeling.

---
*Projeto desenvolvido como parte do curso de Data Science aplicado. Todas as referências bibliográficas estão declaradas no cabeçalho do notebook.*